In [1]:
import tensorflow as tf

In [2]:
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]

In [3]:
# placeholders for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]),name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]),name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]),name = 'weight3')
b = tf.Variable(tf.random_normal([1]),name = 'bias')

In [4]:
hypothesis = x1 * w1 + x2 * w2 + x3* w3 + b

In [5]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis-Y))
# minimize. Need a very small Larning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [6]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(2001): 
    cost_val,hy_val, _ = sess.run([cost,hypothesis,train],
                                 feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,Y:y_data})
    if step % 10 == 0 : 
        print(step,"Cost: ",cost_val, "\nPrediction:\n",hy_val)
        

0 Cost:  59745.27 
Prediction:
 [-67.44374  -74.946434 -77.28048  -80.98253  -58.215004]
10 Cost:  3.863089 
Prediction:
 [148.77756 184.93198 178.78401 197.8642  140.0068 ]
20 Cost:  3.3139005 
Prediction:
 [149.43364 185.71707 179.55946 198.70757 140.60568]
30 Cost:  3.3116488 
Prediction:
 [149.4375  185.71826 179.56252 198.70981 140.60663]
40 Cost:  3.309388 
Prediction:
 [149.43938 185.71707 179.56319 198.70947 140.60576]
50 Cost:  3.3071423 
Prediction:
 [149.44124 185.71588 179.56387 198.70914 140.60489]
60 Cost:  3.3049076 
Prediction:
 [149.44308 185.71468 179.56453 198.70879 140.604  ]
70 Cost:  3.3026638 
Prediction:
 [149.44496 185.7135  179.56522 198.70847 140.60315]
80 Cost:  3.300425 
Prediction:
 [149.4468  185.7123  179.56587 198.7081  140.60228]
90 Cost:  3.2981877 
Prediction:
 [149.44867 185.71114 179.56657 198.70778 140.60143]
100 Cost:  3.2959797 
Prediction:
 [149.4505  185.70995 179.56725 198.70744 140.60057]
110 Cost:  3.2937388 
Prediction:
 [149.45236 185.708

1060 Cost:  3.1021225 
Prediction:
 [149.61015 185.60841 179.62622 198.67181 140.53345]
1070 Cost:  3.100288 
Prediction:
 [149.61165 185.60748 179.6268  198.67142 140.53288]
1080 Cost:  3.0984523 
Prediction:
 [149.61313 185.60652 179.62733 198.671   140.53232]
1090 Cost:  3.0966134 
Prediction:
 [149.61464 185.60559 179.62791 198.67062 140.53177]
1100 Cost:  3.0947773 
Prediction:
 [149.61612 185.60466 179.62846 198.67021 140.53122]
1110 Cost:  3.0929384 
Prediction:
 [149.61761 185.60371 179.62903 198.66982 140.53067]
1120 Cost:  3.091114 
Prediction:
 [149.6191  185.6028  179.6296  198.66942 140.53014]
1130 Cost:  3.0893092 
Prediction:
 [149.62057 185.60185 179.63016 198.66904 140.52959]
1140 Cost:  3.0874772 
Prediction:
 [149.62204 185.60092 179.6307  198.66861 140.52904]
1150 Cost:  3.085654 
Prediction:
 [149.62352 185.59999 179.63127 198.66821 140.5285 ]
1160 Cost:  3.0838351 
Prediction:
 [149.62497 185.59906 179.63179 198.66779 140.52797]
1170 Cost:  3.0820215 
Prediction:


# matrix 로 구현

In [7]:
x_data = [[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

In [8]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32,shape=[None,3]) # x data는 대략적으로 n개를 가질 것이다 => none, x 변수개수는 3개이다 -> 3
Y = tf.placeholder(tf.float32,shape=[None,1]) 

W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')


In [9]:
# Hypothesis
hypothesis = tf.matmul(X,W) + b

In [10]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis-Y))
# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001): 
    cost_val,hy_val, _ = sess.run([cost,hypothesis,train],
                                 feed_dict={X :x_data,Y:y_data})
    if step % 10 == 0 : 
        print(step,"Cost: ",cost_val, "\nPrediction:\n",hy_val)

0 Cost:  108815.96 
Prediction:
 [[-142.40437]
 [-166.19176]
 [-166.27773]
 [-182.75212]
 [-123.91122]]
10 Cost:  3.1697278 
Prediction:
 [[149.40836]
 [184.53613]
 [179.30524]
 [193.57881]
 [143.60374]]
20 Cost:  2.1644993 
Prediction:
 [[150.29611]
 [185.59396]
 [180.3523 ]
 [194.71881]
 [144.40851]]
30 Cost:  2.1554415 
Prediction:
 [[150.30363]
 [185.59384]
 [180.3569 ]
 [194.7236 ]
 [144.40631]]
40 Cost:  2.1464543 
Prediction:
 [[150.30847]
 [185.59052]
 [180.35837]
 [194.72495]
 [144.40169]]
50 Cost:  2.137504 
Prediction:
 [[150.31328]
 [185.58717]
 [180.3598 ]
 [194.72629]
 [144.39706]]
60 Cost:  2.128608 
Prediction:
 [[150.31807]
 [185.58383]
 [180.36122]
 [194.72762]
 [144.39246]]
70 Cost:  2.1197484 
Prediction:
 [[150.32288]
 [185.58055]
 [180.36266]
 [194.72896]
 [144.38786]]
80 Cost:  2.1109617 
Prediction:
 [[150.32764]
 [185.57726]
 [180.36409]
 [194.73029]
 [144.38329]]
90 Cost:  2.1022072 
Prediction:
 [[150.33238]
 [185.57393]
 [180.36551]
 [194.7316 ]
 [144.37871]

830 Cost:  1.5676079 
Prediction:
 [[150.6503 ]
 [185.35382]
 [180.4601 ]
 [194.82175]
 [144.07152]]
840 Cost:  1.5617292 
Prediction:
 [[150.65414]
 [185.35114]
 [180.46121]
 [194.82286]
 [144.06776]]
850 Cost:  1.5558748 
Prediction:
 [[150.65797]
 [185.34846]
 [180.46236]
 [194.82399]
 [144.06401]]
860 Cost:  1.5500524 
Prediction:
 [[150.66182]
 [185.34578]
 [180.4635 ]
 [194.82509]
 [144.06027]]
870 Cost:  1.5442275 
Prediction:
 [[150.66566]
 [185.34314]
 [180.46463]
 [194.82623]
 [144.05653]]
880 Cost:  1.5384854 
Prediction:
 [[150.66948]
 [185.34052]
 [180.46577]
 [194.82733]
 [144.05283]]
890 Cost:  1.5327423 
Prediction:
 [[150.6733 ]
 [185.33788]
 [180.46692]
 [194.82846]
 [144.04912]]
900 Cost:  1.5270357 
Prediction:
 [[150.6771 ]
 [185.33522]
 [180.46803]
 [194.82954]
 [144.04541]]
910 Cost:  1.5213668 
Prediction:
 [[150.6809 ]
 [185.33261]
 [180.46918]
 [194.83066]
 [144.04173]]
920 Cost:  1.5157204 
Prediction:
 [[150.68466]
 [185.33   ]
 [180.47028]
 [194.83177]
 [14

1760 Cost:  1.1331769 
Prediction:
 [[150.96692]
 [185.13402]
 [180.55362]
 [194.91618]
 [143.76054]]
1770 Cost:  1.1295688 
Prediction:
 [[150.96991]
 [185.13197]
 [180.55452]
 [194.91711]
 [143.75761]]
1780 Cost:  1.1259638 
Prediction:
 [[150.97289]
 [185.1299 ]
 [180.55539]
 [194.91803]
 [143.75467]]
1790 Cost:  1.1223695 
Prediction:
 [[150.97585]
 [185.12785]
 [180.55626]
 [194.91896]
 [143.75172]]
1800 Cost:  1.1188198 
Prediction:
 [[150.9788 ]
 [185.12582]
 [180.55713]
 [194.91986]
 [143.74881]]
1810 Cost:  1.1152654 
Prediction:
 [[150.98174]
 [185.12376]
 [180.55798]
 [194.92076]
 [143.74586]]
1820 Cost:  1.1117452 
Prediction:
 [[150.98465]
 [185.12172]
 [180.55885]
 [194.92168]
 [143.74295]]
1830 Cost:  1.1082282 
Prediction:
 [[150.9876 ]
 [185.11967]
 [180.5597 ]
 [194.92256]
 [143.74004]]
1840 Cost:  1.1047385 
Prediction:
 [[150.99051]
 [185.11766]
 [180.56056]
 [194.92348]
 [143.73714]]
1850 Cost:  1.1012574 
Prediction:
 [[150.99342]
 [185.11563]
 [180.56142]
 [194.9

# Lab 4-2
- loading data from file 

In [12]:
import numpy as np

In [15]:
xy = np.loadtxt('data-01-test-score.csv',delimiter=',',dtype=np.float32)

In [16]:
x_data = xy[:,0:-1]  # 전체 n 행 다 가져오고, 처음부터 마지막 열 전까지를 x_data라고 하겠다 
y_data = xy[:,[-1]]  # 전체 n 행 다 가져오고, 마지막 열만 가져온다. 

In [17]:
# Make sure the shape and data are OK
print(x_data.shape,x_data,len(x_data))
print(y_data.shape,y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


### * 파이썬 slicing 방법 연습하기 

In [18]:
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1]) 

W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [19]:
hypothesis = tf.matmul(X,W) + b

In [20]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis-Y))
# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [21]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001): 
    cost_val,hy_val, _ = sess.run([cost,hypothesis,train],
                                 feed_dict={X :x_data,Y:y_data})
    if step % 10 == 0 : 
        print(step,"Cost: ",cost_val, "\nPrediction:\n",hy_val)

0 Cost:  61441.24 
Prediction:
 [[ -85.48183 ]
 [ -92.876625]
 [ -96.48563 ]
 [-107.59768 ]
 [ -66.09163 ]
 [ -51.040756]]
10 Cost:  18.571772 
Prediction:
 [[145.59274]
 [184.90688]
 [177.19293]
 [190.44257]
 [145.79031]
 [105.15185]]
20 Cost:  15.660187 
Prediction:
 [[147.17578]
 [186.77917]
 [179.05362]
 [192.4664 ]
 [147.21283]
 [106.19298]]
30 Cost:  15.566346 
Prediction:
 [[147.20456]
 [186.78288]
 [179.0734 ]
 [192.48541]
 [147.21004]
 [106.18341]]
40 Cost:  15.473236 
Prediction:
 [[147.22273]
 [186.77396]
 [179.08067]
 [192.49086]
 [147.19763]
 [106.16678]]
50 Cost:  15.380783 
Prediction:
 [[147.2408  ]
 [186.76503 ]
 [179.08786 ]
 [192.49619 ]
 [147.18523 ]
 [106.150154]]
60 Cost:  15.288924 
Prediction:
 [[147.25879]
 [186.75609]
 [179.09505]
 [192.5015 ]
 [147.17285]
 [106.13359]]
70 Cost:  15.197655 
Prediction:
 [[147.27672]
 [186.74715]
 [179.10216]
 [192.50677]
 [147.1605 ]
 [106.11707]]
80 Cost:  15.107033 
Prediction:
 [[147.29457]
 [186.7383 ]
 [179.10927]
 [192.5

880 Cost:  9.491403 
Prediction:
 [[148.54723 ]
 [186.11465 ]
 [179.60643 ]
 [192.88542 ]
 [146.28062 ]
 [104.950325]]
890 Cost:  9.438251 
Prediction:
 [[148.56087]
 [186.10785]
 [179.61185]
 [192.88954]
 [146.2711 ]
 [104.93784]]
900 Cost:  9.3855095 
Prediction:
 [[148.57445]
 [186.10106]
 [179.6172 ]
 [192.89362]
 [146.26161]
 [104.92541]]
910 Cost:  9.333066 
Prediction:
 [[148.58798]
 [186.0943 ]
 [179.62256]
 [192.89772]
 [146.25215]
 [104.91301]]
920 Cost:  9.280953 
Prediction:
 [[148.6015 ]
 [186.08755]
 [179.62791]
 [192.9018 ]
 [146.24274]
 [104.90064]]
930 Cost:  9.229212 
Prediction:
 [[148.61497]
 [186.08086]
 [179.63324]
 [192.90585]
 [146.23335]
 [104.88833]]
940 Cost:  9.177818 
Prediction:
 [[148.62837]
 [186.07416]
 [179.63857]
 [192.90991]
 [146.22398]
 [104.87607]]
950 Cost:  9.12675 
Prediction:
 [[148.64174 ]
 [186.06749 ]
 [179.64386 ]
 [192.91396 ]
 [146.21465 ]
 [104.863846]]
960 Cost:  9.076011 
Prediction:
 [[148.65506 ]
 [186.06084 ]
 [179.64914 ]
 [192.91

1620 Cost:  6.3681946 
Prediction:
 [[149.44305]
 [185.6668 ]
 [179.9605 ]
 [193.15865]
 [145.65173]
 [104.13314]]
1630 Cost:  6.3355517 
Prediction:
 [[149.45369]
 [185.66144]
 [179.96469]
 [193.16193]
 [145.6442 ]
 [104.12347]]
1640 Cost:  6.3030868 
Prediction:
 [[149.46432 ]
 [185.65613 ]
 [179.96887 ]
 [193.1652  ]
 [145.63669 ]
 [104.113815]]
1650 Cost:  6.2707963 
Prediction:
 [[149.4749 ]
 [185.6508 ]
 [179.97305]
 [193.16849]
 [145.62917]
 [104.1042 ]]
1660 Cost:  6.238785 
Prediction:
 [[149.48546]
 [185.64554]
 [179.97722]
 [193.17175]
 [145.62172]
 [104.09463]]
1670 Cost:  6.2069416 
Prediction:
 [[149.49599 ]
 [185.64026 ]
 [179.98135 ]
 [193.17502 ]
 [145.61429 ]
 [104.085075]]
1680 Cost:  6.1753254 
Prediction:
 [[149.50645]
 [185.63503]
 [179.98549]
 [193.17827]
 [145.60686]
 [104.07557]]
1690 Cost:  6.1439285 
Prediction:
 [[149.51689]
 [185.62978]
 [179.98958]
 [193.18147]
 [145.59946]
 [104.06608]]
1700 Cost:  6.112698 
Prediction:
 [[149.52731]
 [185.62457]
 [179.99

In [22]:
# Ask my score
print("Your score will be ", sess.run(hypothesis,feed_dict={X:[[100,70,101]]}))
print("Other scores will be ", sess.run(hypothesis,feed_dict={X:[[80,90,120]]}))

Your score will be  [[188.67633]]
Other scores will be  [[154.0072]]


## Queue Runners

In [23]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'],shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key,value = reader.read(filename_queue)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [25]:
# Default values, in case of empty columns. Also specifies the type of the decoded result
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)



In [28]:
# collect batches of csv in 
train_x_batch, train_y_batch = \   # batch로 데이터 빨아들임 
    tf.train.batch([xy[0:-1],xy[-1:]],batch_size=10)  

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [29]:
X = tf.placeholder(tf.float32,shape=[None,3])  # 3, 1주의 
Y = tf.placeholder(tf.float32,shape=[None,1]) 

W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [30]:
hypothesis = tf.matmul(X,W) + b

In [31]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis-Y))
# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [34]:
# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess,coord=coord)

for step in range(2001): 
    x_batch, y_batch = sess.run([train_x_batch,train_y_batch])  # 펌프질을 해서 데이터 가져온다. 
    cost_val,hy_val, _ = sess.run([cost,hypothesis,train],
                                 feed_dict={X :x_data,Y:y_data})
    if step % 10 == 0 : 
        print(step,"Cost: ",cost_val, "\nPrediction:\n",hy_val)
        
coord.request_stop()
coord.join(threads)

0 Cost:  21447.717 
Prediction:
 [[19.390244]
 [16.21202 ]
 [19.803478]
 [20.86664 ]
 [10.921156]
 [ 5.630765]]
10 Cost:  14.010681 
Prediction:
 [[155.86417]
 [180.31866]
 [181.46095]
 [196.91771]
 [136.10358]
 [ 97.92217]]
20 Cost:  12.951701 
Prediction:
 [[156.77228]
 [181.43819]
 [182.5494 ]
 [198.10512]
 [136.96274]
 [ 98.56194]]
30 Cost:  12.876309 
Prediction:
 [[156.7623  ]
 [181.45381 ]
 [182.55042 ]
 [198.10825 ]
 [136.97986 ]
 [ 98.580956]]
40 Cost:  12.801463 
Prediction:
 [[156.74617]
 [181.46193]
 [182.54405]
 [198.10335]
 [136.99123]
 [ 98.59571]]
50 Cost:  12.727039 
Prediction:
 [[156.73006]
 [181.47002]
 [182.5377 ]
 [198.09843]
 [137.00256]
 [ 98.61038]]
60 Cost:  12.653149 
Prediction:
 [[156.71397]
 [181.47804]
 [182.53134]
 [198.09354]
 [137.01382]
 [ 98.625  ]]
70 Cost:  12.57972 
Prediction:
 [[156.69798]
 [181.48608]
 [182.52505]
 [198.08868]
 [137.0251 ]
 [ 98.63959]]
80 Cost:  12.5068245 
Prediction:
 [[156.68202]
 [181.49405]
 [182.51875]
 [198.08379]
 [137

720 Cost:  8.70727 
Prediction:
 [[155.76392]
 [181.95439]
 [182.15715]
 [197.80058]
 [137.68538]
 [ 99.4869 ]]
730 Cost:  8.659616 
Prediction:
 [[155.75107 ]
 [181.96085 ]
 [182.15208 ]
 [197.79655 ]
 [137.69452 ]
 [ 99.498505]]
740 Cost:  8.612275 
Prediction:
 [[155.73828]
 [181.9673 ]
 [182.14706]
 [197.79257]
 [137.70366]
 [ 99.51007]]
750 Cost:  8.565265 
Prediction:
 [[155.7255 ]
 [181.97368]
 [182.14204]
 [197.78857]
 [137.71274]
 [ 99.52159]]
760 Cost:  8.518549 
Prediction:
 [[155.71278]
 [181.98009]
 [182.13705]
 [197.7846 ]
 [137.7218 ]
 [ 99.53308]]
770 Cost:  8.472116 
Prediction:
 [[155.7001  ]
 [181.98645 ]
 [182.13206 ]
 [197.78061 ]
 [137.73083 ]
 [ 99.544525]]
780 Cost:  8.426029 
Prediction:
 [[155.68747]
 [181.9928 ]
 [182.12712]
 [197.77667]
 [137.73984]
 [ 99.55595]]
790 Cost:  8.380197 
Prediction:
 [[155.67488 ]
 [181.99915 ]
 [182.12218 ]
 [197.77274 ]
 [137.74883 ]
 [ 99.567314]]
800 Cost:  8.334687 
Prediction:
 [[155.66232]
 [182.00545]
 [182.11723]
 [197.

1500 Cost:  5.7838635 
Prediction:
 [[154.88028]
 [182.39984]
 [181.81107]
 [197.5203 ]
 [138.32054]
 [100.2812 ]]
1510 Cost:  5.755153 
Prediction:
 [[154.87038]
 [182.40486]
 [181.80719]
 [197.51712]
 [138.32774]
 [100.29003]]
1520 Cost:  5.7266593 
Prediction:
 [[154.86052]
 [182.40984]
 [181.80336]
 [197.51393]
 [138.33493]
 [100.29886]]
1530 Cost:  5.698307 
Prediction:
 [[154.8507 ]
 [182.41484]
 [181.79951]
 [197.51076]
 [138.34209]
 [100.30763]]
1540 Cost:  5.670189 
Prediction:
 [[154.84088]
 [182.41977]
 [181.79568]
 [197.50757]
 [138.3492 ]
 [100.31638]]
1550 Cost:  5.6421847 
Prediction:
 [[154.83112]
 [182.42473]
 [181.79187]
 [197.5044 ]
 [138.35632]
 [100.3251 ]]
1560 Cost:  5.6144214 
Prediction:
 [[154.82138]
 [182.42966]
 [181.78809]
 [197.50125]
 [138.3634 ]
 [100.33379]]
1570 Cost:  5.586823 
Prediction:
 [[154.81166]
 [182.43456]
 [181.7843 ]
 [197.4981 ]
 [138.37045]
 [100.34245]]
1580 Cost:  5.559389 
Prediction:
 [[154.80199]
 [182.43947]
 [181.78053]
 [197.495 