# Tensor Manipulation

In [19]:
import numpy as np

In [20]:
import tensorflow as tf
import pprint

In [27]:
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [28]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape 
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1]) # 4부터 -1의 앞까지 
print(t[:2],t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [29]:
# 2D array
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [30]:
# Shape, Rank, Axis(축)

t = tf.constant([1,2,3,4]) # 랭크는 1, shape은 4
tf.shape(t).eval()

array([4])

In [31]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()  # 랭크는 2, shape은 2,2

array([2, 2])

In [33]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval() # 랭크는 4, shape 은 랭크가 4니까 -> (?,?,?,?) 이렇게 됨 그 다음엔 가장 안으로 들어서 가장 안에 element가 4개라서 (?,?,?,4) 
# -> 그 밖의 []안에 덩어리는 3개라서 (?,?,3,4) ->  그 밖은 2개라서 (?,2,3,4) -> 그밖엔 1개라서 (1,2,3,4)

array([1, 2, 3, 4])

In [ ]:
# 랭크가 4개라면 축 4개임 -> axis
# 축에 각각에 번호를 매김 

### matmul VS multipy 

In [34]:
matrix1 = tf.constant([[1.,2.],[3.,4.]]) # (2,2)
matrix2 = tf.constant([[1.],[2.]]) # (2,1)
print("Metrix 1 shape",matrix1.shape)
print("Metrix 2 shape",matrix2.shape)
tf.matmul(matrix1,matrix2).eval()

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

## Broadcasting 
- shape이 달라도 연산 할 수 있게 해줌 

In [35]:

# Operations betwwen the same shapes
matix1 = tf.constant([[3.,3.]])
matrix2 = tf.constant([[2.,2.]])
(matrix1+matrix2).eval()

array([[3., 4.],
       [5., 6.]], dtype=float32)

In [37]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

## reduce mean
- 평균을 구하는데 줄여서 구한다. 


In [38]:
tf.reduce_mean([1,2],axis=0).eval()

1

In [41]:
x = [[1.,2.],
     [3.,4.]]

tf.reduce_mean(x).eval()

2.5

In [42]:
tf.reduce_mean(x,axis=0).eval()  # 1과 3의 평균은 2가 되고, 2와 4의 평균은 3이 된다. 

array([2., 3.], dtype=float32)

In [43]:
tf.reduce_mean(x, axis=1).eval() # 1과 2의 평균 1.5, 3과 4의 평균 3.5 

array([1.5, 3.5], dtype=float32)

In [44]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

## Reduce sum

In [45]:
tf.reduce_sum(x).eval()

10.0

In [46]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [47]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [48]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis

In [49]:
x = [[0,1,2],
    [2,1,0]]
tf.argmax(x,axis=0).eval()

array([1, 0, 0], dtype=int64)

In [50]:
# 가장 큰 것의 위치
tf.argmax(x,axis=1).eval()

array([2, 0], dtype=int64)

In [51]:
tf.argmax(x,axis=-1).eval()

array([2, 0], dtype=int64)

##  **reshape

In [52]:

t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [55]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:

tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [60]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [62]:
# dimension 추가 

In [61]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

## One hot
- 기본적으로 one hot은 랭크를 하나 더 생성하게 됨 

In [63]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

## Casting

In [64]:
tf.cast([1.8,2.2,3.3,4.9], tf.int32).eval()

array([1, 2, 3, 4])

## stack 
- 쌓는다 

In [65]:

x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones and Zeros like 
- 모양 똑같은 걸로 0이나 1로 채워진 텐서 만들고 싶다 

In [67]:

x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [68]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Zip

In [70]:

for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [71]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
