In [1]:
import numpy as np

In [4]:
# coulmn vector
c = np.array([1,2,3]) # one dimensional array 생성
print(c.shape) # size는 one dimensional array 이고, 크기는 3이다. 

# obtaining a particular entry
print(c[0]) # 첫번째 element

(3,)
1


In [5]:
# row vector
r = np.array([[1,2,3]]) # 큰[] 는 row 이고 [1,2,3] 는 array 자체가 한 element로 등장했고, 첫번째 row의 값이 [1,2,3]
print(r.shape) # 사이즈는 1,3

(1, 3)


In [6]:
# obtaining a particular entry 
print(r[0,1])

2


In [8]:
# creating a matrix with all zeros
a = np.zeros((2,2)) # 사이즈는 2,2
print(a)

# creating a matrix with all ones
b = np.ones((2,2)) # 사이즈는 2,2 인 모든 elements가 1인 행렬 생성 
print(b)

# creating a matrix filled with the same constant
c = np.full((2,2),7) # 2,2이고 모든 상수가 7 
print(c)

# creating a matrix with random values
d = np.random.random((2,2)) # 0~1 사이의 랜덤값 
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.30324673 0.0512756 ]
 [0.97547952 0.72343923]]


In [9]:
# creating a matix 
A = np.array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
# creating another matrix
B = np.array([[11,12,13,14],[15,16,17,18]])
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [11]:
# transpose a matrix
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [12]:
# matrix-matirx multiplication 행렬간 곱셈
np.dot(A,B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [13]:
# matrix-matrix multiplication
# size should match !
np.dot(B,A) # A는 3,2 행렬이고 B는 2,4행렬임 BA하면 4,3이 안맞아서 오류발생

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [37]:
# coefficient matrix A and a vector b
A = np.array([[60,5.5,1],[65,5.0,0],[55,6.0,1]]) # feature값
b = np.array([66,70,78]) # 수명주기 값

In [30]:
A

array([list([60, 5.5, 1]), list([65, 5, 0, 0]), list([55, 6.0, 1])],
      dtype=object)

In [19]:
# identify matrix
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
from numpy.linalg import inv

In [38]:
# computing an inverse
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [39]:
# wrong matrix multiplication (element끼리의 곱임)
A*A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [40]:
# correct matrix multiplication
A.dot(A_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# solution of a linear system
x = A_inv.dot(b)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [42]:
# a better way to solve the same linear system
from numpy.linalg import solve
x = solve(A,b)
x

array([ -0.43478261,  19.65217391, -16.        ])